#!/usr/bin/bash
echo "create"   | ./sql_interpreter_parser.out    
echo "database" | ./sql_interpreter_parser.out     
echo "use"      | ./sql_interpreter_parser.out     
echo "table"    | ./sql_interpreter_parser.out     
echo "tables"   | ./sql_interpreter_parser.out     
echo "show"     | ./sql_interpreter_parser.out     
echo "insert"   | ./sql_interpreter_parser.out     
echo "select"   | ./sql_interpreter_parser.out     
echo "update"   | ./sql_interpreter_parser.out     
echo "delete"   | ./sql_interpreter_parser.out     
echo "drop"     | ./sql_interpreter_parser.out     
echo "exit"     | ./sql_interpreter_parser.out
echo create     | ./sql_interpreter_parser.out    
echo database   | ./sql_interpreter_parser.out     
echo use        | ./sql_interpreter_parser.out     
echo table      | ./sql_interpreter_parser.out     
echo tables     | ./sql_interpreter_parser.out     
echo show       | ./sql_interpreter_parser.out     
echo insert     | ./sql_interpreter_parser.out     
echo select     | ./sql_interpreter_parser.out     
echo update     | ./sql_interpreter_parser.out     
echo delete     | ./sql_interpreter_parser.out     
echo drop       | ./sql_interpreter_parser.out     
echo exit       | ./sql_interpreter_parser.out   
echo "2019E103" | ./sql_interpreter_parser.out
echo "iosahksa" | ./sql_interpreter_parser.out